## Numpy

In [1]:
import numpy as np
a = np.array([(1,2,3,4,5),(6,7,8,9,10)]) 
# multiple dimensions can be included by () inside []

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
print('number of dimensions :',a.ndim)
print('shape(number of rows and columns) :', a.shape)

number of dimensions : 2
shape(number of rows and columns) : (2, 5)


In [3]:
import os
os.getcwd()

'/Users/varsharamkumar/Documents/Python_learning/Ram_learning_notebooks'

In [8]:
b = a.reshape(5,2) #changing the rows and columns
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [14]:
np.linspace(start=1, stop=5,num=10) #return the number of equal elements between numbers

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [18]:
t = np.linspace(start=1, stop=5,num=10)
print('maximum :',t.max() )
print('sum :',t.sum())

maximum : 5.0
sum : 30.0


In [20]:
#axis concept
#axis = 0, columns
#axis = 1, rows

r = np.array([(1,2,3),(4,5,6)])
#column based addition
print('column based addition :', r.sum(axis = 0))
print('row based addition :', r.sum(axis = 1))

column based addition : [5 7 9]
row based addition : [ 6 15]


In [21]:
np.sqrt(r)

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [22]:
np.std(r)

1.707825127659933

All addition, subtraction, multiplication and division are matrix wise

In [26]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a+b ) #addition
print(a-b) #subtraction
print(a+b) # multiplication
print(a/b) # division

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


concatenation is called - stacking
1. vertical stacking and 
2. horizontal stacking

In [29]:
np.vstack((a,b)) # vertical or row addition

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
np.hstack((a,b)) # horizontal or column level concatenation/

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [32]:
np.ravel(a) # changing all dimensions into single column

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange() #Shift + tab for interactive optionss

array([1, 2, 3, 4])